name: pytorch
channels:
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/pytorch
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/pytorch/
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge/
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main/
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free/
  - defaults
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=1_gnu
  - blas=1.0=mkl
  - blosc=1.21.0=h9c3ff4c_0
  - brotli=1.0.9=h7f98852_6
  - brotli-bin=1.0.9=h7f98852_6
  - brunsli=0.1=h9c3ff4c_0
  - bzip2=1.0.8=h7f98852_4
  - c-ares=1.18.1=h7f98852_0
  - c-blosc2=2.0.4=h5f21a17_1
  - ca-certificates=2021.10.8=ha878542_0
  - certifi=2021.10.8=py39hf3d152e_1
  - cfitsio=4.0.0=h9a35b8e_0
  - charls=2.2.0=h9c3ff4c_0
  - cloudpickle=2.0.0=pyhd8ed1ab_0
  - cudatoolkit=11.1.1=h6406543_9
  - cycler=0.11.0=pyhd8ed1ab_0
  - cytoolz=0.11.2=py39h3811e60_1
  - dask-core=2021.12.0=pyhd8ed1ab_0
  - ffmpeg=4.3=hf484d3e_0
  - fonttools=4.28.5=py39h3811e60_0
  - freetype=2.10.4=h0708190_1
  - fsspec=2021.11.1=pyhd8ed1ab_0
  - giflib=5.2.1=h36c2ea0_2
  - gmp=6.2.1=h58526e2_0
  - gnutls=3.6.13=h85f3911_1
  - imagecodecs=2021.11.20=py39h571908b_1
  - imageio=2.13.4=pyh239f2a4_0
  - intel-openmp=2021.4.0=h06a4308_3561
  - jbig=2.1=h7f98852_2003
  - jpeg=9d=h36c2ea0_0
  - jxrlib=1.1=h7f98852_2
  - kiwisolver=1.3.2=py39h1a9c180_1
  - krb5=1.19.2=h48eae69_3
  - lame=3.100=h7f98852_1001
  - lcms2=2.12=hddcbb42_0
  - ld_impl_linux-64=2.36.1=hea4e1c9_2
  - lerc=3.0=h9c3ff4c_0
  - libaec=1.0.6=h9c3ff4c_0
  - libblas=3.9.0=12_linux64_mkl
  - libbrotlicommon=1.0.9=h7f98852_6
  - libbrotlidec=1.0.9=h7f98852_6
  - libbrotlienc=1.0.9=h7f98852_6
  - libcblas=3.9.0=12_linux64_mkl
  - libcurl=7.80.0=h494985f_1
  - libdeflate=1.8=h7f98852_0
  - libedit=3.1.20191231=he28a2e2_2
  - libev=4.33=h516909a_1
  - libffi=3.4.2=h7f98852_5
  - libgcc-ng=11.2.0=h1d223b6_11
  - libgfortran-ng=11.2.0=h69a702a_11
  - libgfortran5=11.2.0=h5c6108e_11
  - libgomp=11.2.0=h1d223b6_11
  - libiconv=1.16=h516909a_0
  - liblapack=3.9.0=12_linux64_mkl
  - libnghttp2=1.43.0=ha19adfc_1
  - libpng=1.6.37=h21135ba_2
  - libssh2=1.10.0=ha35d2d1_2
  - libstdcxx-ng=11.2.0=he4da1e4_11
  - libtiff=4.3.0=h6f004c6_2
  - libuv=1.42.0=h7f98852_0
  - libwebp-base=1.2.1=h7f98852_0
  - libzlib=1.2.11=h36c2ea0_1013
  - libzopfli=1.0.3=h9c3ff4c_0
  - locket=0.2.0=py_2
  - lz4-c=1.9.3=h9c3ff4c_1
  - matplotlib-base=3.5.1=py39h2fa2bec_0
  - mkl=2021.4.0=h06a4308_640
  - mkl-service=2.4.0=py39h7e14d7c_0
  - mkl_fft=1.3.1=py39h0c7bc48_1
  - mkl_random=1.2.2=py39hde0f152_0
  - munkres=1.1.4=pyh9f0ad1d_0
  - ncurses=6.2=h58526e2_4
  - nettle=3.6=he412f7d_0
  - networkx=2.6.3=pyhd8ed1ab_1
  - numpy=1.21.2=py39h20f2e39_0
  - numpy-base=1.21.2=py39h79a1101_0
  - olefile=0.46=pyh9f0ad1d_1
  - openh264=2.1.1=h780b84a_0
  - openjpeg=2.4.0=hb52868f_1
  - openssl=3.0.0=h7f98852_2
  - packaging=21.3=pyhd8ed1ab_0
  - pandas=1.3.5=py39hde0f152_0
  - partd=1.2.0=pyhd8ed1ab_0
  - pillow=8.4.0=py39ha612740_0
  - pip=21.3.1=pyhd8ed1ab_0
  - pyparsing=3.0.6=pyhd8ed1ab_0
  - python=3.9.7=hf930737_3_cpython
  - python-dateutil=2.8.2=pyhd8ed1ab_0
  - python_abi=3.9=2_cp39
  - pytorch=1.10.0=py3.9_cuda11.1_cudnn8.0.5_0
  - pytorch-mutex=1.0=cuda
  - pytz=2021.3=pyhd8ed1ab_0
  - pywavelets=1.2.0=py39hce5d2b2_1
  - pyyaml=6.0=py39h3811e60_3
  - readline=8.1=h46c0cb4_0
  - scikit-image=0.19.1=py39hde0f152_0
  - scipy=1.7.3=py39hee8e79c_0
  - setuptools=59.4.0=py39hf3d152e_0
  - six=1.16.0=pyh6c4a22f_0
  - snappy=1.1.8=he1b5a44_3
  - sqlite=3.37.0=h9cd32fc_0
  - tifffile=2021.11.2=pyhd8ed1ab_0
  - tk=8.6.11=h27826a3_1
  - toolz=0.11.2=pyhd8ed1ab_0
  - torchaudio=0.10.0=py39_cu111
  - torchvision=0.11.1=py39_cu111
  - typing_extensions=4.0.1=pyha770c72_0
  - tzdata=2021e=he74cb21_0
  - wheel=0.37.0=pyhd8ed1ab_1
  - xz=5.2.5=h516909a_1
  - yaml=0.2.5=h516909a_0
  - zfp=0.5.5=h9c3ff4c_8
  - zlib=1.2.11=h36c2ea0_1013
  - zstd=1.5.0=ha95c52a_0
  - pip:
    - h5py==3.6.0
    - hdf5storage==0.1.18
prefix: /data2/yanmuge/yanmuge/anaconda3/envs/pytorch
